### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by AdesojiCodeMaster**
### The Authors:  **Adesoji and Luciano **

[Live Demo Link](https://repl.it/repls/HightechPerfumedFormula#main.rb)

In this project, we  used;

### repl.it

Thank You for taking the time to review our code. 💐

Thanks!

### CODE REVIEW

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project;

### The Project Title:  **Custom Enumerable Methods in Ruby.**

### The Authors:  **Adesoji and Luciano **

[Live Demo Link](https://repl.it/repls/HightechPerfumedFormula#main.rb)

In this project, we  used;

### Ruby
### github/workflows

Thank You for taking the time to review our code. 💐

Thanks!

**Comment by krys2fa** [comment]
## Great job so far @AdesojiCodeMaster and @lucianosarno 👏 
Your repo looks professional with good commit messages and a professional README 💪 

Just a few more adjustments to complete the project.
### Status: Changes Required ♻️ 
- [REQUIRED] Move the above comment requesting the review to the description of this PR. 
You can click on the edit option after clicking the three dots on the upper right corner of the description box.

- [ ]  [REQUIRED] Most of your methods make use of your custom `my_each` method but they have no access to this method. 
Either put all methods in the same file or make reference to the file with the `my_each` method in all the other files.

- [ ]  [REQUIRED] Your `my_each`, `my_each_with_index` methods should behave exactly like ruby's `each`, `each_with_index` methods.
Your custom methods usually return nil when tested with arrays, ranges and hashes (with or without blocks passed).

- [ ]  [REQUIRED] The following custom methods do not return the same output as their equivalent ruby methods:
         - `my_all`
         - `my_any`
         - `my_none`
         - `my_count`
         - `my_map`
         - `my_inject`
Kindly fix this. Please check [this resource](https://ruby-doc.org/core-2.7.1/Enumerable.html) out. You can test your custom methods with the examples given in the documentation.

- [ ]  [REQUIRED] Your `multiply_els` method should accept an array as an argument and multiply all the elements of the array together using the `my_inject` method.

That's all.

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project again after the required corrections have been made on the project;

### The Project Title:  **Custom Enumerable Methods in Ruby.**

### The Authors:  **Adesoji and Luciano **

[Live Demo Link](https://repl.it/repls/HightechPerfumedFormula#main.rb)

In this project, we  used;

### Ruby
### github/workflows
### repl.it

Thank You for taking the time to review our code. 💐

Thanks!

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :wave:
Status: Changes Required :recycle: 

Great job on implementing most of the features :+1: 
Let's cover a few more details together.

### Methods "my_"
- [ ]  Refactoring for everyone in the list below :arrow_down: 

I know you already are following the documentation but let me remind it one more time.
These are our resources =>

1. https://ruby-doc.org/core-2.6.5/Enumerable.html
2. https://ruby-doc.org/core-2.6.5/Enumerator.html

Every one of our methods "my_..." should return the same things as these documents are implementing.
I will write the requirements and give an example.

##  my_each

- when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- when a block is given when self is a range returns the range itself after calling the given block once for each element in self

:camera_flash:  **Screenshot: What documentation says about the inputs of "each" method**
each

1. It takes a block and returns an object.
2. It returns an enumerator if it doesn't take any input.
3. It takes arguments and it takes a block and returns an object.
4. It takes an argument and returns an enumerator.

:camera_flash:  **We also have examples for "each" in the document**
each examples
You can see the examples for every input here.

## my_each_with_index
- when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- when a block is given when self is a range returns the range itself after calling the given block once for each element in self

## my_count
- returns the number of items in enum through enumeration

## my_map
- executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

## my_inject
- raises an Error when no block or argument is given
- searches for the longest word in an array of strings
- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method

## multiply_els
- accepts an array as an argument and multiplies all the elements of the array together using #my_inject

##

That's it. I know you can do this with your level of experience! :1st_place_medal: 
With all my respect...

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project again. The adjustments were made based on TSEs recommendations;

### The Project Title:  **Custom Enumerable Methods in Ruby.**

### The Authors:  **Adesoji and Luciano **

In this project, we  used;

### Ruby
### github/workflows

Thank You for taking the time to review our code. 💐

Thanks!

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project again. The corrections were made based on TSEs recommendations ;

### The Project Title:  **Custom Enumerable Methods in Ruby.**

### The Authors:  **Adesoji and Luciano **

In this project, we  used;

### Ruby
### github/workflows

Thank You for taking the time to review our code. 💐

Thanks!

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
